DROP TABLE IF EXISTS User;
CREATE TABLE User (
id INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL UNIQUE,
nickname VARCHAR(255),
phone_number VARCHAR(25) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS Password;
CREATE TABLE Password (
id INT(10) PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
user_id INT(10) NOT NULL UNIQUE,
hash VARCHAR(255),
FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);