DROP TABLE IF EXISTS User;
CREATE TABLE User (
  id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  name VARCHAR(255) NOT NULL,
  nickname VARCHAR(255),
  phone_number VARCHAR(25) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_id int NOT NULL,
  CONSTRAINT user_unique_id UNIQUE(id),
  CONSTRAINT user_unique_name UNIQUE(name),
  CONSTRAINT user_unique_email UNIQUE(email),
  CONSTRAINT user_unique_password_id UNIQUE(password_id)
);

DROP TABLE IF EXISTS Password;
CREATE TABLE Password (
  id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  user_id int,
  hash VARCHAR(255),
  CONSTRAINT password_unique_id UNIQUE(id)
);

DROP TABLE IF EXISTS Community;
CREATE TABLE Community (
  id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  name varchar(255),
  admin_id int,
  description varchar(550)
);


ALTER TABLE User ADD FOREIGN KEY (password_id) REFERENCES Password(id);
ALTER TABLE Password ADD FOREIGN KEY (user_id) REFERENCES User(id);
ALTER TABLE Community ADD FOREIGN KEY (admin_id) REFERENCES User(id);